<?php

namespace App\Console;

use Illuminate\Console\Scheduling\Schedule;
use Illuminate\Foundation\Console\Kernel as ConsoleKernel;

class Kernel extends ConsoleKernel
{
    /**
     * Define the application's command schedule.
     *
     * @param  \Illuminate\Console\Scheduling\Schedule  $schedule
     * @return void
     */
    protected function schedule(Schedule $schedule)
    {
        // Auto generate daily attendance setiap hari jam 23:59
        $schedule->call(function () {
            \App\Filament\Pages\PresensiKelas::autoGenerateDailyAttendance();
        })->dailyAt('23:59')
            ->name('auto-generate-daily-attendance')
            ->description('Generate daily attendance records automatically')
            ->withoutOverlapping()
            ->runInBackground();

        // Contoh scheduler lainnya yang mungkin berguna:

        // Backup database setiap hari jam 02:00
        // $schedule->command('backup:database')
        //          ->dailyAt('02:00')
        //          ->name('daily-database-backup')
        //          ->description('Daily database backup');

        // Cleanup log files setiap minggu
        // $schedule->command('log:clear')
        //          ->weekly()
        //          ->sundays()
        //          ->at('01:00')
        //          ->name('weekly-log-cleanup')
        //          ->description('Clean up old log files');

        // Send reminder emails setiap jam kerja
        // $schedule->call(function () {
        //     // Logic untuk mengirim reminder
        // })->weekdays()
        //   ->hourly()
        //   ->between('08:00', '17:00')
        //   ->name('hourly-reminders')
        //   ->description('Send hourly reminders during work hours');
    }

    /**
     * Register the commands for the application.
     *
     * @return void
     */
    protected function commands()
    {
        $this->load(__DIR__ . '/Commands');

        require base_path('routes/console.php');
    }

    /**
     * Get the timezone that should be used by default for scheduled events.
     *
     * @return \DateTimeZone|string|null
     */
    protected function scheduleTimezone()
    {
        return 'Asia/Jakarta'; // Sesuaikan dengan timezone Indonesia
    }
}
